<template>
  <div>
    <h2 class="page-title">站点身份</h2>

    <!-- ADR-036：站点身份管理（与桌面设置页「站点标识」区对齐）——查看/修改/重新生成 -->
    <div class="card">
      <div class="identity-row">
        <div class="identity-label">当前站点标识</div>
        <div class="identity-value">{{ siteId || '-' }}</div>
        <el-tag :type="sourceTagType" size="small">{{ sourceLabel }}</el-tag>
      </div>

      <el-alert
        v-if="configPinned"
        type="warning"
        :closable="false"
        title="当前由配置/环境变量 Site:Id 锁定"
        description="在线修改只写入本地库，重启后配置值仍优先。如需永久变更，请直接修改配置（appsettings 或环境变量 Site__Id）。"
        style="margin-top:16px"
      />

      <el-alert
        v-if="restartHint"
        type="warning"
        :closable="false"
        title="已保存，需重启后全面生效"
        description="采集/转发/告警/状态页在启动时读取站点标识，重启后全面生效；配置同步（边缘→中心 push）会立即使用新值。"
        style="margin-top:16px"
      />

      <!-- 仅 Admin 可修改/重新生成（后端 AdminOnly 兜底；前端仅 UX） -->
      <div v-if="isAdmin" class="identity-edit">
        <el-input
          v-model="editSiteId"
          placeholder="小写字母/数字开头，可含连字符，≤32 位，非 default"
          maxlength="32"
          style="max-width:360px"
          @keyup.enter="onSave"
        />
        <el-button type="primary" :loading="saving" @click="onSave">保存</el-button>
        <el-button type="danger" plain :loading="regenerating" @click="onRegenerate">重新生成</el-button>
      </div>

      <div v-if="statusText" class="identity-status" :class="statusOk ? 'ok' : 'err'">{{ statusText }}</div>

      <div class="identity-note">
        首次启动自动生成唯一标识；保存/重新生成后重启生效。格式：小写字母/数字开头、可含连字符、≤32 位
        （MQTT topic 与 URL 友好）。同一标识被多台机器使用会造成订阅端数据混淆。
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getSiteIdentity, updateSiteIdentity, regenerateSiteIdentity, type SiteIdentity } from '../../api/site'
import { loadMe } from '../../api/user'

const siteId = ref('')
const source = ref('')
const configPinned = ref(false)
const restartHint = ref(false)

const editSiteId = ref('')
const saving = ref(false)
const regenerating = ref(false)
const statusText = ref('')
const statusOk = ref(true)

const me = loadMe()
const isAdmin = computed(() => me?.role === 'Admin')

const sourceLabel = computed(() => {
  const map: Record<string, string> = {
    Configured: '配置锁定',
    Persisted: '本地持久化',
    AutoGenerated: '自动生成'
  }
  return map[source.value] ?? source.value ?? '-'
})

const sourceTagType = computed(() => {
  if (source.value === 'Configured') return 'warning'
  if (source.value === 'AutoGenerated') return 'info'
  return 'success'
})

function apply(id: SiteIdentity | null) {
  if (!id) return
  siteId.value = id.siteId
  source.value = id.source
  configPinned.value = id.configPinned
  restartHint.value = id.restartRequired
  editSiteId.value = id.siteId
}

async function refresh() {
  try {
    apply(await getSiteIdentity())
  } catch {
    /* 401 由拦截器跳转，其余静默 */
  }
}

async function onSave() {
  const value = editSiteId.value.trim()
  if (!value) {
    statusText.value = '站点标识不能为空'
    statusOk.value = false
    return
  }
  saving.value = true
  try {
    const id = await updateSiteIdentity(value)
    apply(id)
    statusText.value = `已保存：${id?.siteId ?? ''}（重启后全面生效）`
    statusOk.value = true
  } catch (e: any) {
    statusText.value = `保存失败：${e?.response?.data?.error?.message ?? e?.message ?? '未知错误'}`
    statusOk.value = false
  } finally {
    saving.value = false
  }
}

async function onRegenerate() {
  try {
    await ElMessageBox.confirm(
      '重新生成将替换当前站点标识，重启后上行 topic 与配置同步归属性切换到新值，是否继续？',
      '重新生成站点标识',
      { confirmButtonText: '重新生成', cancelButtonText: '取消', type: 'warning' }
    )
  } catch {
    return
  }
  regenerating.value = true
  try {
    const id = await regenerateSiteIdentity()
    apply(id)
    statusText.value = `已重新生成：${id?.siteId ?? ''}（重启后全面生效）`
    statusOk.value = true
  } catch (e: any) {
    statusText.value = `重新生成失败：${e?.response?.data?.error?.message ?? e?.message ?? '未知错误'}`
    statusOk.value = false
  } finally {
    regenerating.value = false
  }
}

onMounted(refresh)
</script>

<style scoped>
.page-title { margin-bottom: 20px; }
.card { background: var(--bg-card); border: 1px solid var(--border); border-radius: 8px; padding: 20px; max-width: 760px; }
.identity-row { display: flex; align-items: center; gap: 14px; flex-wrap: wrap; }
.identity-label { font-size: 13px; color: var(--text-dim, #909399); }
.identity-value { font-size: 18px; font-weight: 700; font-family: ui-monospace, SFMono-Regular, Consolas, monospace; word-break: break-all; }
.identity-edit { display: flex; gap: 10px; align-items: center; margin-top: 20px; flex-wrap: wrap; }
.identity-status { margin-top: 12px; font-size: 13px; }
.identity-status.ok { color: #67c23a; }
.identity-status.err { color: #f56c6c; }
.identity-note { margin-top: 16px; font-size: 12px; color: var(--text-dim, #909399); line-height: 1.6; border-top: 1px dashed var(--border, #e4e7ed); padding-top: 12px; }
</style>
