import client from './client'
import type { ApiResponse } from './types'

/// 站点身份视图（ADR-036 站点身份管理，与桌面设置页「站点标识」区对齐）
export interface SiteIdentity {
  siteId: string
  /// Configured（配置/环境变量锁定）/ Persisted（本地持久化）/ AutoGenerated（自动生成）
  source: string
  /// 是否由配置/环境变量 Site:Id 锁定（在线修改只写本地库，重启后配置仍优先）
  configPinned: boolean
  /// 修改/重新生成后是否需要重启全面生效（配置同步 push 会立即用新值）
  restartRequired: boolean
}

/// 查看当前站点身份
export async function getSiteIdentity(): Promise<SiteIdentity | null> {
  const { data } = await client.get<ApiResponse<SiteIdentity>>('/site')
  return data.data ?? null
}

/// 修改站点标识（仅 Admin）：校验后持久化到本地库，重启后全面生效
export async function updateSiteIdentity(siteId: string): Promise<SiteIdentity | null> {
  const { data } = await client.put<ApiResponse<SiteIdentity>>('/site', { siteId })
  return data.data ?? null
}

/// 重新生成站点标识（仅 Admin）：加密随机生成并持久化，重启后全面生效
export async function regenerateSiteIdentity(): Promise<SiteIdentity | null> {
  const { data } = await client.post<ApiResponse<SiteIdentity>>('/site/regenerate')
  return data.data ?? null
}
