<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NitroGateway.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NitroGateway.Domain\NitroGateway.Domain.csproj" />
    <ProjectReference Include="..\NitroGateway.Shared\NitroGateway.Shared.csproj" />
    <ProjectReference Include="..\NitroGateway.Persistence\NitroGateway.Persistence.csproj" />
    <ProjectReference Include="..\NitroGateway.Transport\MQTT\NitroGateway.Transport.MQTT.csproj" />
    <ProjectReference Include="..\NitroGateway.Telemetry\NitroGateway.Telemetry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
