namespace NitroGateway.Webapi.Models;

/// <summary>
/// 站点身份视图（站点身份管理 API，ADR-036）：当前生效站点标识 + 来源 + 生效提示。
/// 与桌面设置页「站点标识」区语义对齐：查看 / 修改 / 重新生成。
/// </summary>
public sealed class SiteIdentityDto
{
    /// <summary>当前生效的站点标识（MQTT topic 第三层 nitrogateway/{siteId}/… 与配置同步归属性）</summary>
    public string SiteId { get; init; } = "";

    /// <summary>来源枚举名：Configured（配置/环境变量锁定）/ Persisted（本地持久化）/ AutoGenerated（自动生成）</summary>
    public string Source { get; init; } = "";

    /// <summary>是否由配置/环境变量 Site:Id 锁定（在线修改只写本地库，重启后配置仍优先）</summary>
    public bool ConfigPinned { get; init; }

    /// <summary>
    /// 是否需要重启生效：GET 恒为 false（反映当前生效态）；修改/重新生成响应为 true——
    /// 采集/转发/告警/状态页在启动时读取 Site:Id，改后需重启全面生效；配置同步 push 会立即用新值。
    /// </summary>
    public bool RestartRequired { get; init; }
}

/// <summary>修改站点标识的请求体（PUT /api/site）</summary>
public sealed class SiteIdentityUpdateRequest
{
    /// <summary>目标站点标识：小写字母/数字开头、可含连字符、≤32 位、非 default</summary>
    public string? SiteId { get; set; }
}
