using Microsoft.Extensions.Configuration;
using NitroGateway.Persistence.Sqlite;
using NitroGateway.Shared;
using NitroGateway.Webapi.Services;
using Xunit;

namespace NitroGateway.UnitTests;

/// <summary>
/// Web 端 SiteIdProvider（ADR-036）：解析顺序（配置 → app_meta → 自动生成）与
/// 来源标记 SiteIdSource（供站点身份管理 API 区分「配置锁定 / 本地持久化 / 自动生成」）。
/// </summary>
public sealed class WebSiteIdProviderTests
{
    /// <summary>与 SiteIdProvider.AppMetaKey（internal）一致的 app_meta 键名</summary>
    private const string AppMetaKey = "site_id";

    private sealed class MemoryAppMetaStore : IAppMetaStore
    {
        public Dictionary<string, string> Values { get; } = new();
        public Task<string?> GetAsync(string key, CancellationToken ct = default)
            => Task.FromResult(Values.TryGetValue(key, out var v) ? v : null);
        public Task SetAsync(string key, string value, CancellationToken ct = default)
        {
            Values[key] = value;
            return Task.CompletedTask;
        }
    }

    private static IConfiguration Config(string? siteId)
    {
        var builder = new ConfigurationBuilder();
        if (siteId is not null)
            builder.AddInMemoryCollection(new Dictionary<string, string?> { ["Site:Id"] = siteId });
        return builder.Build();
    }

    [Fact]
    public void Ctor_configured_valid_marks_Configured()
    {
        var store = new MemoryAppMetaStore();

        var provider = new SiteIdProvider(Config("env-site"), store);

        Assert.Equal("env-site", provider.Current);
        Assert.Equal(SiteIdSource.Configured, provider.Source);
        Assert.False(store.Values.ContainsKey(AppMetaKey)); // 配置优先不落库
    }

    [Fact]
    public void Ctor_stored_valid_marks_Persisted()
    {
        var store = new MemoryAppMetaStore();
        store.Values[AppMetaKey] = "stored-site";

        var provider = new SiteIdProvider(Config(null), store);

        Assert.Equal("stored-site", provider.Current);
        Assert.Equal(SiteIdSource.Persisted, provider.Source);
    }

    [Fact]
    public void Ctor_nothing_usable_generates_and_persists_marked_AutoGenerated()
    {
        var store = new MemoryAppMetaStore();

        var provider = new SiteIdProvider(Config("default"), store);

        Assert.True(SiteOptions.IsValidSiteId(provider.Current));
        Assert.Equal(SiteIdSource.AutoGenerated, provider.Source);
        Assert.Equal(provider.Current, store.Values[AppMetaKey]);
    }

    [Fact]
    public void Save_persists_and_flips_source_to_Persisted()
    {
        var store = new MemoryAppMetaStore();
        var provider = new SiteIdProvider(Config(null), store);

        var result = provider.Save("plant-b");

        Assert.True(result.IsSuccess);
        Assert.Equal("plant-b", provider.Current);
        Assert.Equal(SiteIdSource.Persisted, provider.Source);
        Assert.Equal("plant-b", store.Values[AppMetaKey]);
    }

    [Fact]
    public void Regenerate_persists_and_flips_source_to_Persisted()
    {
        var store = new MemoryAppMetaStore();
        var provider = new SiteIdProvider(Config(null), store);

        var value = provider.Regenerate();

        Assert.True(SiteOptions.IsValidSiteId(value));
        Assert.Equal(SiteIdSource.Persisted, provider.Source);
        Assert.Equal(value, store.Values[AppMetaKey]);
    }
}
