using Microsoft.Extensions.Configuration;
using NitroGateway.Persistence.Sqlite;
using NitroGateway.Shared;

namespace NitroGateway.Webapi.Services;

/// <summary>
/// 站点标识来源（站点身份管理 API 用）：区分「配置锁定」与「本地持久化可改」，
/// 供前端决定是否允许在线修改/重新生成并提示生效时机（ADR-036）。
/// </summary>
public enum SiteIdSource
{
    /// <summary>配置/环境变量 Site:Id 锁定：在线修改只写 app_meta，重启后配置仍优先</summary>
    Configured,

    /// <summary>app_meta 持久化值：可由站点身份 API 修改，重启保持</summary>
    Persisted,

    /// <summary>首次启动自动生成并持久化（存储与 Persisted 相同，仅标记来源）</summary>
    AutoGenerated
}

/// <summary>
/// 站点标识提供者（ADR-036）：解析、保存与重新生成生效的 siteId。
/// Web 收敛为纯边缘网关后，本实例持有本站点唯一身份，供设备落库与配置同步 push 使用。
/// </summary>
public interface ISiteIdProvider
{
    /// <summary>当前生效的站点标识</summary>
    string Current { get; }

    /// <summary>当前站点标识来源（配置锁定 / 本地持久化 / 自动生成）</summary>
    SiteIdSource Source { get; }

    /// <summary>保存站点标识（先校验）；失败返回带错误信息的 OperationResult</summary>
    OperationResult Save(string siteId);

    /// <summary>自动生成新站点标识并持久化，返回新值</summary>
    string Regenerate();
}

/// <summary>站点标识解析结果：生效值 + 来源（供启动期一次解析后持久持有）</summary>
internal readonly record struct SiteResolution(string SiteId, SiteIdSource Source);

/// <summary>
/// 生效 siteId 解析顺序：配置/环境变量（Site:Id）→ 本地 app_meta 持久化 → 自动生成并持久化。
/// 保留值 "default"（旧版 appsettings 缺省）视为未初始化，一律进入自动生成路径；
/// 启动时 Program 把解析结果写回配置，采集/转发/告警/同步统一取用（ADR-036）。
/// </summary>
public sealed class SiteIdProvider : ISiteIdProvider
{
    /// <summary>app_meta 持久化键名（M006 建表；与桌面 site.json 语义一致）</summary>
    internal const string AppMetaKey = "site_id";

    private readonly IAppMetaStore _store;
    private string _current;
    private SiteIdSource _source;

    /// <param name="configuration">应用配置（Site:Id）</param>
    /// <param name="store">app_meta 键值持久化（启动时表已由迁移建好）</param>
    public SiteIdProvider(IConfiguration configuration, IAppMetaStore store)
    {
        _store = store;
        // 启动期解析（仅一次）：阻塞等待 app_meta 查询，表在 InitializeDatabase 后已存在。
        var resolution = ResolveAsync(configuration, store).GetAwaiter().GetResult();
        _current = resolution.SiteId;
        _source = resolution.Source;
    }

    /// <inheritdoc />
    public string Current => _current;

    /// <inheritdoc />
    public SiteIdSource Source => _source;

    /// <summary>
    /// 解析生效站点标识。配置值合法（非空、非 default、格式合规）优先；
    /// 其次本地 app_meta 持久化；都不可用时自动生成并持久化，保证首次启动即有唯一 siteId。
    /// </summary>
    internal static async Task<SiteResolution> ResolveAsync(IConfiguration configuration, IAppMetaStore store)
    {
        var configured = configuration["Site:Id"]?.Trim();
        if (SiteOptions.IsValidSiteId(configured))
            return new SiteResolution(configured!, SiteIdSource.Configured);

        var stored = (await store.GetAsync(AppMetaKey))?.Trim();
        if (SiteOptions.IsValidSiteId(stored))
            return new SiteResolution(stored!, SiteIdSource.Persisted);

        var generated = SiteOptions.GenerateSiteId();
        await store.SetAsync(AppMetaKey, generated);
        return new SiteResolution(generated, SiteIdSource.AutoGenerated);
    }

    /// <inheritdoc />
    public OperationResult Save(string siteId)
    {
        var value = siteId?.Trim() ?? "";
        if (!SiteOptions.IsValidSiteId(value))
            return OperationResult.Failure(OperationalError.Validation(
                "站点标识不合法：小写字母/数字开头，可含连字符，≤32 位，且不能为 default"));

        _store.SetAsync(AppMetaKey, value).GetAwaiter().GetResult();
        _current = value;
        _source = SiteIdSource.Persisted;
        return OperationResult.Success();
    }

    /// <inheritdoc />
    public string Regenerate()
    {
        var value = SiteOptions.GenerateSiteId();
        _store.SetAsync(AppMetaKey, value).GetAwaiter().GetResult();
        _current = value;
        _source = SiteIdSource.Persisted;
        return value;
    }
}
